steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

# [START get-creds]
- id: 'get-creds'
  name: 'google/cloud-sdk'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      gcloud secrets versions access latest --secret=project_creds > project_creds.json
      mv project_creds.json modules/
      cd modules/
      pwd
      ls
# [END get-creds]

# [START tf-init]
- id: 'tf init'
  name: 'hashicorp/terraform:0.11.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      pwd
      cd modules/
      ls
      terraform init
# [END tf-init]

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:0.11.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd modules/
      ls
      terraform plan -var-file=myproject.tfvars
# [END tf-plan]

# [START tf-destroy]
- id: 'tf destory'
  name: 'hashicorp/terraform:0.11.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd modules/
      terraform destroy --auto-approve -var-file=myproject.tfvars
# [END tf-destory]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:0.11.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd modules/
      terraform apply --auto-approve -var-file=myproject.tfvars
# [END tf-apply]      
