steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
- id: 'tf init'
  name: 'hashicorp/terraform:0.13.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd modules/
      terraform init

# [START get-creds]
- id: 'get-creds'
  name: 'alpine'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      gcloud secrets versions access latest --secret=project_creds > project_creds.json
      pwd
      ls
# [END get-creds]

# [START tf-plan]
- id: 'tf plan'
  name: 'ubuntu'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      pwd
      ls
      cd /workspace
      echo "new test"
      ls
      cat project_creds.json
      export creds=$(cat project_creds.json)
      env
      #cd modules/
      #terraform plan -var-file=myproject.tfvars
# [END tf-plan]

# [START tf-apply]
#- id: 'tf apply'
#  name: 'hashicorp/terraform:0.13.6'
#  entrypoint: 'sh'
#  args: 
#  - '-c'
#  - | 
#      cd modules/
#      terraform apply --auto-approve -var-file=myproject.tfvars
# [END tf-apply]      
