steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
      if [ $BRANCH_NAME == "dev" ]
      then
      echo "you are on the dev branch and will build your infrastructure in the dev workspace"
      else
      echo "you are on a different branch and will build your infrastructure in the default workspace"
      fi

# [START get-creds]
- id: 'get-creds'
  name: 'google/cloud-sdk'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      gcloud secrets versions access latest --secret=project_creds > project_creds.json
      mv project_creds.json modules/
      cd modules/
# [END get-creds]

# [START get-slackurl]
- id: 'get-slackurl'
  name: 'google/cloud-sdk'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      gcloud secrets versions access latest --secret=slack-webhook-url >> present.txt
      if [ -f present.txt ]
      then
      export SLACK_WEBHOOK=$(gcloud secrets versions access latest --secret=slack-webhook-url)
      echo "***********************"
      echo "export of webhook variable complete"
      echo "***********************"
      else
      echo "***********************"
      echo "file is not found no slack url could be established"
      echo "***********************"
      fi  
      env
# [END get-slackurl]

# [START tf-notify]
- id: 'tf notify'
  name: 'cloudposse/slack-notifier'
  entrypoint:
  dir: 'modules/'
  args: 
  - '-c'
  - |
      -webhook_url "$SLACK_WEBHOOK" \
      -user_name "CodeFresh" \
      -icon_emoji ":white_check_mark:" \
      -fallback "Deployed to Staging environment" \
      -color "good" \
      -pretext "Added XYZ to feature-104" \
      -author_name "Auto Deploy Robot" \
      -author_link "https://cloudposse.com/wp-content/uploads/sites/29/2018/02/small-cute-robot-square.png" \
      -author_icon "https://cloudposse.com/wp-content/uploads/sites/29/2018/02/small-cute-robot-square.png" \
      -title "Environment Updated" \
      -title_link "http://demo1.cloudposse.com" \
      -text "The latest changes have been deployed" \
      -thumb_url "https://cloudposse.com/wp-content/uploads/sites/29/2018/02/SquareLogo2.png" \
      -footer "Helm Deployment" \
      -footer_icon "https://cloudposse.com/wp-content/uploads/sites/29/2018/02/kubernetes.png" \
      -field1_title "Environment" \
      -field1_value "Staging" \
      -field1_short true \
      -field2_title "Namespace" \
      -field2_value "feature-104" \
      -field2_short true
      env

# [END tf-notify]

# [START tf-init]
- id: 'tf init'
  name: 'hashicorp/terraform:0.13.6'
  entrypoint: 'sh'
  dir: 'modules/'
  args: 
  - '-c'
  - |
      terraform init
# [END tf-init]

# [START tf-fmt]
- id: 'tf fmt'
  name: 'hashicorp/terraform:0.13.6'
  entrypoint: 'sh'
  dir: 'modules/'
  args: 
  - '-c'
  - |
      echo "Terraform format"
      terraform fmt
# [END tf-fmt]

# [START tf-validate]
- id: 'tf validate'
  name: 'hashicorp/terraform:0.13.6'
  entrypoint: 'sh'
  dir: 'modules/'
  args: 
  - '-c'
  - |
      echo "Terraform validate"
      terraform validate
# [END tf-validate]

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:0.13.6'
  entrypoint: 'sh'
  dir: 'modules/'
  args: 
  - '-c'
  - | 
      if [ $BRANCH_NAME == "dev" ]
      then
      terraform workspace select dev
      else
      terraform workspace select default
      fi
      terraform workspace list
      terraform plan -var-file=myproject.tfvars
# [END tf-plan]

# [START tf-destroy]
- id: 'tf destory'
  name: 'hashicorp/terraform:0.13.6'
  entrypoint: 'sh'
  dir: 'modules/'
  args: 
  - '-c'
  - | 
      terraform workspace list
      terraform destroy --auto-approve -var-file=myproject.tfvars
# [END tf-destory]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:0.13.6'
  entrypoint: 'sh'
  dir: 'modules/'
  args: 
  - '-c'
  - | 
      terraform workspace list
      terraform apply --auto-approve -var-file=myproject.tfvars
# [END tf-apply]      

# [START tf-cleanup]
- id: 'tf cleanup'
  name: 'hashicorp/terraform:0.13.6'
  entrypoint: 'sh'
  dir: 'modules/'
  args: 
  - '-c'
  - | 
      terraform workspace list
      terraform destroy --auto-approve -var-file=myproject.tfvars
# [END tf-cleanup]