Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@EmanuelBurgess 
EmanuelBurgess
/
solutions-terraform-cloudbuild-gitops
forked from GoogleCloudPlatform/solutions-terraform-cloudbuild-gitops
0
0529
Code
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
solutions-terraform-cloudbuild-gitops/cloudbuild.yaml
@fernandorubbo
fernandorubbo Initial commit
Latest commit 556e82f on 29 May 2019
 History
 1 contributor
92 lines (87 sloc)  2.56 KB
  
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
- id: 'tf init'
  name: 'hashicorp/terraform:0.13.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      terraform init 
# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:0.13.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      terraform plan -auto-approve -var-file=/modules/myproject.tfvars
# [END tf-plan]

# [START tf-apply]
#- id: 'tf apply'
#  name: 'hashicorp/terraform:0.13.6'
#  entrypoint: 'sh'
#  args: 
#  - '-c'
#  - | 
#      if [ -d "environments/$BRANCH_NAME/" ]; then
#        cd environments/$BRANCH_NAME      
#        terraform apply -auto-approve
#      else
#        echo "***************************** SKIPPING APPLYING *******************************"
#        echo "Branch '$BRANCH_NAME' does not represent an oficial environment."
#        echo "*******************************************************************************"
#      fi
# [END tf-apply]      
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
Loading complete